- util/print.zig
- util/timer.zig
- zbench.zig
- use `std.time.nanoTimestamp` instead of `std.time.microTimestamp`
- adds a safety-check before calling `quickSort`(did we actually record any durations?)
- adds a saftey-check before calling the calculation of avg. duration - note that this might conflict with #12 
- adds some comments / TODOs; you might want to remove them as you deem adequate
> Change from microsecond to nanosecond timer resolution

- zbench.zig
closes https://github.com/hendriknielaender/zBench/issues/11
With this modification, the `calculateAverage` method will use the count of recorded durations as the denominator when calculating the average duration per operation, which should address the concern of incorrect or inconsistent results due to multiple increments of self.totalOperations.
> fix: use duration array length for average calculation

- examples/basic.zig
- examples/bubble_sort.zig
- zbench.zig
- Removed automatic incrementing of operations count in `stop` method.
- Removed unused `incrementOperations` method.
- Introduced `setOperations` method for explicit count setting.
- Updated example usage and tests to align with new counting logic.
Removed Automatic Incrementing:
Removed the line `self.totalOperations += 1;` from the stop method of the Benchmark struct to prevent automatic incrementing of the operations count.
This change is based on the observation that automatic incrementing may not accurately represent the total operations performed.
Introduced setOperations Method:
Added a `setOperations` method to the Benchmark struct, allowing explicit setting of the operations count as needed.
This method provides a way to explicitly set the operations count to a specific value, …
> feat(benchmark): refine operations counting logic

- examples/basic.zig
- examples/bubble_sort.zig
- zbench.zig
- pass allocator by value instead of reference
- deinitialize the allocator after `run`
- update examples, showing how to deinitialize the results memory
> close memory leak with testing allocator

- build.zig
- examples/basic.zig
- examples/bubble_sort.zig
- examples/sleep.zig
- util/timer.zig
- zbench.zig
This will address #17 and #18.
> Migrate to std.time.Timer and tweak benchmark boundaries

- build.zig
https://github.com/hendriknielaender/zBench/issues/22
- The script has been modularized into distinct functions: `setupLibrary`, `setupTesting`, `setupExamples`, and `setupDocumentation`. This modularization separates concerns, making the script more readable and easier to maintain.
- Each function is responsible for a specific aspect of the build process, thereby reducing complexity and improving the overall structure of the script.
- Comments and documentation within the script have been added or updated to reflect these changes, providing clear guidance on the purpose and functionality of each part of the script.
- A significant enhancement in the setupTesting function is the dynamic discovery and inclusion of `.zig` test files from specified directories.
- This is achieved by …
> Refactor build.zig for Enhanced Readability and Dynamic Test Inclusion

- build.zig
- tests.zig
- zbench.zig
This adds standard deviation and displays it in the pretty-print. Also added respective tests. Part of #29
> Add standard-deviation metric

- tests.zig
- zbench.zig
Part of #29. Makes it so that subsequent pretty-prints align nicely with eachother. Also now displays the number of runs performed in the pretty-print.
> Pretty print fixup

- README.md
- zbench.zig
- Switch to snake-case for fields in Benchmark
- Update benchmark-output example in README
- Use ArrayList.clearRetainingCapacity instead of deiniting and initing Benchmark.durations everytime we reset
- Use std.math.maxInt instead of writing the maximum as a literal
> Various small changes/improvments

- build.zig
- zbench.zig
1) I noticed that there are debug prints in the build script; those can mix in with other console output if `zbench` is an indirect dependency (e.g. my [check_filetimes](https://codeberg.org/FObersteiner/check_filetime) demo for [zdt](https://codeberg.org/FObersteiner/zdt) got a "Failed to open directory x" since zbench is used in zdt). Scoped logging should avoid this. See also : https://ziggit.dev/t/best-practices-writing-to-stdout/2760
2) Also, there seems to be mix of printing to stdout and stderr (std.debug.print). IMHO, this should be stdout only since we do not want to signal errors when running benchmarks (stderr output can be interpreted as exit(1)).
> introduce scoped logging & revise debug print

- util/format.zig
- zbench.zig
After 1389ebfc3795b we forget to print a newline in the for-loop within BenchmarkResults.prettyPrint, causing messed-up formatting. We also forgot to call BenchmarkResults.getColor when determining the color for total-time. Both of these are now fixed. Also moved prettyPrintHeader to util/format.zig for consistency.
> Fix small formatting bug, move prettyPrintHeader to utils

- examples/basic.zig
- examples/bubble_sort.zig
- examples/sleep.zig
- zbench.zig
This was done to circumvent hendriknielaender#49, which is (most likely) caused by a bug in the compiler. Closes #49.
> Added init/deinit to BenchmarkResults and updated examples

- examples/basic.zig
- util/format.zig
- util/os/linux.zig
- util/os/osx.zig
- util/os/windows.zig
- util/platform.zig
- zbench.zig
Implement enhanced system information retrieval for Linux, macOS, and Windows within `platform.zig`. This includes accurate fetching of CPU name, core count, and total memory.
Tested on:
> feat: display sys infos

- zbench.zig
This function was moved to format.zig, but we had forgotten to remove it from zbench.zig
> Remove dead function zbench.prettyPrintHeader

- README.md
- examples/basic.zig
- zbench.zig
This PR introduces lifecycle hooks, providing users with greater control and flexibility over their benchmark setup and teardown processes. These hooks allow for custom actions at various stages of the benchmarking lifecycle, enabling precise environment management and setup/teardown operations.
- **Lifecycle Hooks**: Implement `beforeAll`, `afterAll`, `beforeEach`, and `afterEach` hooks.
- `beforeAll`: Executes once before all benchmarks begin.
- `afterAll`: Executes once after all benchmarks have completed.
- `beforeEach`: Executes before each individual benchmark iteration.
- `afterEach`: Executes after each individual benchmark iteration.
These hooks are particularly beneficial for complex benchmarks requiring specific setup and teardown operations, ensuring each test runs under the …
> feat(benchmark): add lifecycle hooks for enhanced benchmark control

- build.zig
- tests.zig
- zbench.zig
The last item of the durations array was being left out of the sort, and sometimes I was seeing larger p75 values than p995, which is nonsensical. I've fixed the issue and added some tests and asserts that check for sanity.
The average and standard deviation functions looked like they could use some tweaks too.
> Fix percentile calculation, there was an issue with sorting

- build.zig
- examples/parameterised.zig
- zbench.zig
This implementation is pretty simple and allows any number and type of parameters to be used, I think the API is pretty pleasant too. Despite the `@ptrCast`s and `anyopaque`s I'm pretty confident it's type safe as long as benchmarks are always added using the API functions.
close https://github.com/hendriknielaender/zBench/issues/55
> Parameterised benchmarks

- build.zig
- examples/bubble_sort.zig
- examples/hooks.zig
- examples/parameterised.zig
- examples/progress.zig
- examples/sleep.zig
- examples/systeminfo.zig
- util/runner.zig
- zbench.zig
Allows to get results as they become available and show a progress bar type display, and allows to limit memory use by freeing results when they're received.
> Add an incremental API for running benchmarks

- README.md
- build.zig
- examples/basic.zig
- examples/bubble_sort.zig
- examples/hooks.zig
- examples/json.zig
- examples/progress.zig
- examples/systeminfo.zig
- util/format.zig
- util/platform.zig
- util/runner.zig
- util/runner/types.zig
- util/statistics.zig
- zbench.zig
Some of these make more sense when recording allocations as well as durations. These changes should make the memory tracking PR much less bulky.
- Move `Statistics` into its own module and parameterise it by type, so it can hold `u64`s for nanoseconds and `usize`s for bytes.
- Compute statistics on demand rather than pre-computing them in `Result`.
- Add `Reading` and `Readings` types, so it can carry more than just nanoseconds without changing most code.
- Try a different approach to formatting using the extensibility methods from `std.fmt`. This inlines a fair bit of code but it seems easier to inspect and modify than being hidden behind a bunch of functions.
- Add an example for the JSON output.
- Simplify a few examples to be more focused.
If necessary, I can split these into separate …
> Various refactors

- examples/basic.zig
- zbench.zig
It seems to have been scribbling over the allocator in `Benchmarks`, resulting in segfaults, I couldn't pin down exactly how it was doing it but either removing the `setName()` and `maybeRefresh()` calls or removing it altogether worked to eliminate the segfaults. Further investigation needed before adding it back in.
> Remove std.Progress

- build.zig
- examples/json.zig
- examples/memory_tracking.zig
- util/runner.zig
- util/runner/types.zig
- util/statistics.zig
- util/tracking_allocator.zig
- zbench.zig
Adds a custom `Allocator` wrapper which keeps track of the allocated memory, then record the maximum allocation readings in the `Runner` alongside timing readings and carry them into the `Result`. I've added equivalent statistics for memory use as for timings, but maybe we only need something simpler?
Current output:
```
benchmark              runs     total time     time/run (avg ± σ)     (min ... max)                p75        p99        p995
-----------------------------------------------------------------------------------------------------------------------------
My Benchmark           10       1.118ms        111.879us ± 14.24us    (98.058us ... 136.68us)      125.995us  136.68us   136.68us
My Benchmark [MEMORY]                          2.000KiB ± 0B          (2.000KiB ... 2.000KiB) …
```
> Add memory allocation tracking

- examples/json.zig
- examples/memory_tracking.zig
- examples/progress.zig
- util/runner/types.zig
- util/statistics.zig
- zbench.zig
There isn't much cost to making a temporary copy of them for sorting, IMHO, and it preserves the link between the readings for each run. It makes the code simpler too in that `Statistics.init` doesn't need to be called with sorted readings now.
> Don't mutate the readings when calculating statistics

- build.zig
std.Build.LazyPath.path has been deprecated in Zig 0.12 and will be removed in 0.13. `std.Build.path` works for both 0.12 stable and the current 0.13-dev branch of Zig. This PR is to limit the changes needed for the 0.13 adaption in the future.
> use std.Build.path function instead of std.Build.LazyPath.path

- README.md
- docs/install.md
Enhance README and Add installation documentation
- Added a Table of Contents (TOC) for better navigation.
- Moved detailed installation instructions to docs/install.md.
> chore: add TOC & created install.md

- zbench.zig
This pull request tries to fix [Handling Long Benchmark Names in Output Formatting](https://github.com/hendriknielaender/zBench/issues/32). 
I followed the second suggested enhancement : Ensure that the formatting remains consistent and readable regardless of name length.
> fix: truncate long benchmark name

- examples/sleep.zig
While running all examples, I noticed that the sleep example output was not very clean. I added a new line to make it properly aligned
> chore: improve output lisibility

- .github/workflows/deploy-docs.yml
- .github/workflows/zig.yml
- .gitignore
- README.md
- build.zig
- build.zig.zon
- examples/progress.zig
- util/os/windows.zig
- util/platform.zig
- zbench.zig
Closes https://github.com/hendriknielaender/zBench/issues/84
> build: use zig 0.13.0

- build.zig
- docs/hooks.md
- examples/bubble_sort_hooks.zig
This PR adds documentation and a new example to illustrate the lifecycle hook feature.
> docs: add hooks documentation and example

- docs/install.md
Install guide is outdated. I used Zig 0.13.0 and got following error.
```
/home/kumiko/test_heap/build.zig:41:8: error: no field or member function named 'addAnonymousModule' in 'Build.Step.Compile'
exe.addAnonymousModule("zbench", .{
~~~^~~~~~~~~~~~~~~~~~~
/usr/lib/zig/std/Build/Step/Compile.zig:1:1: note: struct declared here
const builtin = @import("builtin");
^~~~~
```
> chore: update zig 0.13 install guide

- .github/workflows/deploy-docs.yml
- .github/workflows/zig.yml
The `setup-zig` action is not maintained anymore.
> ci: upgrade to mlugg/setup-zig@v1

- util/runner.zig
- zbench.zig
> number of iterations limited by type

- README.md
- build.zig
- build.zig.zon
- examples/shuffling_allocator.zig
- util/shuffling_allocator.zig
- zbench.zig
closes https://github.com/hendriknielaender/zBench/issues/92
This PR adds support for the ShufflingAllocator to the zBench, providing an option to benchmark  with an allocator that randomizes memory allocation patterns.
ShufflingAllocator is a memory allocator that randomizes memory patterns to help identify potential use-after-free bugs or memory layout dependencies in code. It maintains "shuffle arrays" of memory slots and may return previously freed memory when allocating, helping identify code that incorrectly assumes deterministic memory allocation patterns.
1. Added dependency on `shuffling-allocator` v0.1.10 in `build.zig.zon`
2. Enhanced the `Config` struct with a new field:
```zig
/// Use the ShufflingAllocator if true (experimental).
/// This can be combined with …
```
> feat: add shuffling allocator
